name: Check-LinkError

on:
  - push
  - pull_request_target

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          fail: true
          args: --verbose './**/*.md'
          format: 'markdown'
          output: 'lychee/out.md'

      - name: Output the result
        if: ${{ (github.event_name != 'push') && always() }}
        id: output_result
        run: |
#          echo "# 🤖 Generated LinkReport by Action using lychee\n" > .dummy.report.md
          cat lychee/out.md > .dummy.report.md
          report="$(cat .dummy.report.md)"
          echo "REPORT_LINK=$report" >> $GITHUB_ENV
          echo $report

      - name: Run Python Script Output Commenter
        uses: OrjanSkarnes/pull-request-commenter@1.2.3
        with:
          comment-body: ${{ env.REPORT_LINK }}
          comment-search-includes: "# 🤖 Generated LinkReport by Action using lychee"
          comment-title: "# 🤖 Generated LinkReport by Action using lychee"
          comment-edit-mode: replace
          fail-on-output: true
          github-token: ${{ secrets.GH_PAT }}
