name: Check-LinkError

on:
  - push
  - pull_request_target

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          fail: false
          args: --verbose './**/*.md'
          format: 'markdown'
          output: out.md

      - name: Output the result
        id: output_result
        run: |
          cat out.md > .dummy.report.md
          cat .dummy.report.md

      - uses: labring-actions/Pull-Request-Comments-hidden-tags@v1.3
        if: ${{ (github.event_name != 'push') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          filename: .dummy.report.md
          tag: report-linkChecker

      - name: Exit result
        run: |
          echo "Output exit code is ${{ env.lychee_exit_code }}"
          exit ${{ env.lychee_exit_code }}
