name: 🚀 Tagpr for GitHub Actions
on:
  push:
    branches:
      - new-tagpr
jobs:
  tagpr:
    runs-on: ubuntu-22.04
#    permissions:
#      contents: read
#      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger Release Workflow(only when tagged)
        uses: actions/github-script@v6
        if: "steps.tagpr.outputs.tag != ''"
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: "refs/tags/${{ steps.tagpr.outputs.tag }}",
            })